"""empty message

Revision ID: 4cbe5d50c2cb
Revises: 
Create Date: 2024-07-22 21:52:12.043574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbe5d50c2cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carteira',
    sa.Column('id_carteira', sa.Integer(), nullable=False),
    sa.Column('carteira_nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_carteira')
    )
    op.create_table('cripto',
    sa.Column('id_cripto', sa.Integer(), nullable=False),
    sa.Column('cripto_name', sa.String(length=80), nullable=False),
    sa.Column('cripto_apelido', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id_cripto')
    )
    op.create_table('crypto_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carteira_saldo',
    sa.Column('id_saldo', sa.Integer(), nullable=False),
    sa.Column('carteira_id', sa.Integer(), nullable=False),
    sa.Column('cripto_id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['carteira_id'], ['carteira.id_carteira'], ),
    sa.ForeignKeyConstraint(['cripto_id'], ['cripto.id_cripto'], ),
    sa.PrimaryKeyConstraint('id_saldo')
    )
    op.create_table('transacao',
    sa.Column('id_trans', sa.Integer(), nullable=False),
    sa.Column('cripto_name', sa.String(length=50), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('preco', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('taxa', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('tipo_transacao', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['destino_id'], ['carteira.id_carteira'], ),
    sa.ForeignKeyConstraint(['origem_id'], ['carteira.id_carteira'], ),
    sa.PrimaryKeyConstraint('id_trans')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao')
    op.drop_table('carteira_saldo')
    op.drop_table('crypto_price')
    op.drop_table('cripto')
    op.drop_table('carteira')
    # ### end Alembic commands ###
