"""empty message

Revision ID: 7ab1fe1302f7
Revises: 
Create Date: 2024-08-30 20:27:21.736488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab1fe1302f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptocurrencies',
    sa.Column('crypto_id', sa.Integer(), nullable=False),
    sa.Column('crypto_name', sa.String(), nullable=False),
    sa.Column('crypto_symbol', sa.String(), nullable=False),
    sa.Column('crypto_status', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('crypto_id'),
    sa.UniqueConstraint('crypto_name'),
    sa.UniqueConstraint('crypto_symbol')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('prices',
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('price_crypto_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_consult_datetime', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['price_crypto_id'], ['cryptocurrencies.crypto_id'], ),
    sa.PrimaryKeyConstraint('price_id')
    )
    op.create_table('wallet_balances',
    sa.Column('balance_id', sa.Integer(), nullable=False),
    sa.Column('balance_wallet_id', sa.Integer(), nullable=False),
    sa.Column('balance_crypto_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['balance_crypto_id'], ['cryptocurrencies.crypto_id'], ),
    sa.PrimaryKeyConstraint('balance_id')
    )
    op.create_table('wallets',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('wallet_user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_name', sa.String(), nullable=False),
    sa.Column('wallet_network', sa.String(), nullable=False),
    sa.Column('wallet_status', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['wallet_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    op.create_table('transactions',
    sa.Column('transactions_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('payment_wallet_id', sa.Integer(), nullable=False),
    sa.Column('receiving_wallet_id', sa.Integer(), nullable=True),
    sa.Column('crypto_payment_id', sa.Integer(), nullable=False),
    sa.Column('crypto_payment_price', sa.Float(), nullable=False),
    sa.Column('crypto_payment_quantity', sa.Float(), nullable=False),
    sa.Column('total_paid', sa.Float(), nullable=False),
    sa.Column('crypto_receive_id', sa.Integer(), nullable=False),
    sa.Column('crypto_receive_price', sa.Float(), nullable=False),
    sa.Column('crypto_receive_quantity', sa.Float(), nullable=False),
    sa.Column('total_received', sa.Float(), nullable=False),
    sa.Column('crypto_fee_id', sa.Integer(), nullable=False),
    sa.Column('crypto_fee_price', sa.Float(), nullable=False),
    sa.Column('crypto_fee_quantity', sa.Float(), nullable=False),
    sa.Column('total_fee', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['crypto_fee_id'], ['cryptocurrencies.crypto_id'], ),
    sa.ForeignKeyConstraint(['crypto_payment_id'], ['cryptocurrencies.crypto_id'], ),
    sa.ForeignKeyConstraint(['crypto_receive_id'], ['cryptocurrencies.crypto_id'], ),
    sa.ForeignKeyConstraint(['payment_wallet_id'], ['wallets.wallet_id'], ),
    sa.ForeignKeyConstraint(['receiving_wallet_id'], ['wallets.wallet_id'], ),
    sa.PrimaryKeyConstraint('transactions_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('wallets')
    op.drop_table('wallet_balances')
    op.drop_table('prices')
    op.drop_table('users')
    op.drop_table('cryptocurrencies')
    # ### end Alembic commands ###
